Change the "time" variable name
The "time" name conflicts with the variable "time" in \.platformio\packages\toolchain-xtensa\xtensa-lx106-elf\include\time.h:59:11
Which causes a compilation error when building the project.